### ISSUE TITLE
Add 'blacklist' to config.php

### ISSUE THREAD

**Issue by kitar** [sjelfull/craft3-bugsnag#11]
Thanks for nice plugin!

I've copied config.php to config/bugsnag.php but got some error when reporting.

`Invalid argument supplied for foreach() in /myapp/vendor/superbig/craft3-bugsnag/src/Bugsnag.php:73`

I think we need to add `'blacklist' => []'` to config.php.

**Comment by sjelfull** [comment]
Thanks for reporting. I'll have a fix out soon.

**Comment by kitar** [comment]
Thanks for the fix!
