### ISSUE TITLE
JavaScript notifier doesn't work

### ISSUE THREAD

**Issue by benface** [sjelfull/craft3-bugsnag#18]
I added the following Twig snippet to my template as mentioned in the docs:

```
{% do view.registerAssetBundle('superbig\\bugsnag\\assetbundles\\frontend\\FrontEndAsset') %}
```

And I see that it adds the following HTML...

...in the `<head>`:
```html
<script src="//d2wy8f7a9ursnm.cloudfront.net/v6/bugsnag.min.js" data-apikey="[my-api-key]" data-releasestage="dev"></script>
```

...and in the `<body>`:
```html
<script>
    var Bugsnag = Bugsnag || {};Bugsnag.user = {"id":"1","name":"Benoît Rouleau","email":"[my-email]"};Bugsnag.notifyReleaseStages = ["staging","production"];
</script>
```

But then if I have an error in my JS code:

```html
<script>
  throw 'error';
</script>
```

...nothing happens! So I looked at the [`bugsnag-js` documentation](https://docs.bugsnag.com/platforms/javascript/#cdn), and I cannot find any reference to the `data-apikey` or `data-releasestage` attributes, or the `Bugsnag` variable with a capital `B`. In fact, when I `console.log(Bugsnag)`, I only see the `user` and `notifyReleaseStages` keys added by the code above. So I'm not sure where those things are coming from, maybe it used to work in an old version or something, but now it looks like it's not doing anything at all. I was able to make it work by simply adding this code as mentioned in the `bugsnag-js` documentation:

```
window.bugsnagClient = bugsnag('my-api-key');
```

**Comment by sjelfull** [comment]
This should work now after updating it to support the latest version of the JS client.
