### ISSUE TITLE
Support for environment variables?

### ISSUE THREAD

**Issue by johndwells** [sjelfull/craft3-bugsnag#20]
Subject says it all! :)

**Comment by sjelfull** [comment]
Probably not since you have to add it manually everywhere - i'll add it.

**Comment by johndwells** [comment]
Yeah, I know it can be a pain - but if just for the `serverApiKey`, it would be handy.

:)

**Comment by sjelfull** [comment]
`serverApiKey` and the newly added `browserApiKey` will now be parsed for env variables/aliases.

**Comment by johndwells** [comment]
You are my hero Fred!
