### ISSUE TITLE
Craft's exit tag with a 404 status parameter isn't treated as a 404

### ISSUE THREAD

**Issue by petehjfd** [sjelfull/craft3-bugsnag#29]
Hi

We are ignoring 404 errors using the example blacklists code from the plugin documentation.  This succesfully ignores 404s that are caused by a user visiting a URL that doesn't exists, e.g. http://www.example.com/this-does-not-exist

However, we have some templates where we check for the existence of, for example, and entry and manually return a 404 if it does not exist.  We do this using Craft's {% exit %} tag, e.g.

```
{% exit 404 %}
```

The bugsnag plugin does not ignore these errors, as we would expect it to.

Is there an additional type of exception we should check for?  Or is this a bug in the plugin?

Thanks

**Comment by engram-design** [comment]
Looks like the `{% exit %}` tag handles things differently, and actually throws another error, so it's hard to manage. You can using the following:

```php
<?php

use yii\web\NotFoundHttpException;
use Twig\Error\RuntimeError;

return [
    'blacklist' => [
        [
            'label' => '404 errors etc',
            'class' => function($exception) {
                // Handle errors thrown in Twig via `{% exit %}` tags
                if ($exception instanceof RuntimeError) {
                    $exception = $exception->getPrevious();
                }

                if ($exception instanceof NotFoundHttpException && $exception->statusCode === 404) {
                    return false;
                }

                return true;
            },
        ],
    ],
];
```

Calling `{% exit %}` in Twig will throw a `Twig\Error\RuntimeError` first, and we use `$exception = $exception->getPrevious();` to get the previous exception, which is what you'd expect as the native Yii exceptions.
