### ISSUE TITLE
release stage always set to production

### ISSUE THREAD

**Issue by CodyMcMichael** [sjelfull/craft3-bugsnag#3]
No matter what I put in the release stage field bugsnag reports as production. Is this something that is hardcoded? I notice one can set the config to take an array of stages, it might be nice for the gui to function the same way.

I also noticed when using the bugsnag.php config, the setting gui reflects the changes but can't update, how do you suppose handling this? Could these update each other, or if the bugsnag.php config exists a check occur and in the bugsnag settings page give an info message: 'It looks like your settings are being set via `bugsnag.php` config. Please make your changes there.

**Comment by sjelfull** [comment]
If I understand you correctly:

Config overrides work the same way everywhere in Craft, meaning the bugsnag.php options will always override whatever you enter into the settings GUI.

What you see in the GUI will write to the database, not the bugsnag.php file.

As for the problem with it always being set to production, I see now that I never passed whatever you have set the release stage to.

Will have a new release out soon that fixes this.

**Comment by sjelfull** [comment]
The GUI doesn't have all the config options as I haven't got much time these days to add this, but open to pull requests.

**Comment by CodyMcMichael** [comment]
I'll be glad to fix it for you! I'll open up a pull request.
