### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by jamiepittock** [sjelfull/craft3-bugsnag#30]
Hey Fred, are you planning on upgrading this plugin for Craft 4?

**Comment by johnwbaxter** [comment]
Plus one on this!!

**Comment by engram-design** [comment]
We've recently acquired this plugin from the Superbig team. Read our [blog post](https://verbb.io/blog/some-plugins-from-superbig) for more details.

**Comment by engram-design** [comment]
Added in [4.0.0](https://github.com/verbb/bugsnag/releases/tag/4.0.0)
