### ISSUE TITLE
Blacklist for 404s no longer working in Craft 4

### ISSUE THREAD

**Issue by petehjfd** [sjelfull/craft3-bugsnag#35]
### Describe the bug

We have recently started updating our sites to Craft 4 and have noticed a sudden increase in 404 bug reports in Bugsnag.

We have added 404s to the blackkist but it appears that this is no longer working.

Our blacklist looks like this:

```php
'blacklist' => [
    [
        'label' => '404 errors etc',
        'class' => function($exception) {
            // Handle errors thrown in Twig via `{% exit %}` tags
            if ($exception instanceof RuntimeError) {
                $exception = $exception->getPrevious();
            }

            if ($exception instanceof NotFoundHttpException && $exception->statusCode === 404) {
                return false;
            }

            return true;
        },
    ],
],
```

### Steps to reproduce

1. Be running Craft 4
2. Add 404s to the blacklist
3. Trigger a 404

### Craft CMS version

4.3.1

### Plugin version

4.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Hmm, 404 errors are certainly not getting through to Bugsnag with your exact code in place for me.

Anything else worth mentioning about your setup? Are you triggering any errors in your templates? Is the local, or live?

**Comment by petehjfd** [comment]
That's a shame, I was hoping it would be easy to replicate/fix!

The plugin is enabled in production only (and that is where we are experiencing this issue).

We are triggering errors in templates in some cases / on some sites (i.e. with `{% exit 404 %}`), but most of the errors we are seeing are for 'normal' 404 errors.  For example one of the 404s we see a lot is on requests for /autodiscover/autodiscover.xml (which is obviously bots looking for files that don't exist).

We're experiencing this across a variety of sites.  I can't think of anything in the site setup that would apply to them all.

The only thing I can think of is that as part of the Craft 4 upgrade we have updated various entry scripts and configuration files (as per https://craftcms.com/docs/4.x/upgrade.html#entry-script).  One of the changes is updating variable names in the .env file, including changing ENVIRONMENT to CRAFT_ENVIRONMENT.  This is a long shot, but is it possible that the plugin is no longer recognising the environment because we have changed this variable name?

**Comment by engram-design** [comment]
Yeah, quite strange. And Bugsnag is certainly capturing the 404s, as soon as I remove the exception rule for the blacklist setting. I've also checked not non-web requests triggering 404s via Curl, and that's also correctly handled. I've also test this on a live site on a server, with all the usual production settings in place.

I've also checked when using it alongside Retour, just in case their 404-handling messes things up, but no dice.

I'll keep at it.

**Comment by petehjfd** [comment]
Thanks, let me know if I can provide any more info that might help.

**Comment by petehjfd** [comment]
Hi @engram-design

We've realised that this was caused by the:

```php
use yii\web\NotFoundHttpException;
use Twig\Error\RuntimeError;
```

being missing from the top of the config file.

This didn't seem to be a problem in Craft 3 somehow, but apparently became a problem in Craft 4.

Apologies for the false alarm and thanks again for your help.

**Comment by engram-design** [comment]
Ah, glad you got to the bottom of it at least!
