### ISSUE TITLE
Blacklist field not showing

### ISSUE THREAD

**Issue by bymayo** [sjelfull/craft3-bugsnag#36]
### Describe the bug

When editing the Bugsnag settings in Craft CMS the "Blacklist" field doesn't show

![CleanShot 2023-07-05 at 16 02 46@2x](https://github.com/verbb/bugsnag/assets/522877/a86f8b1c-0284-4fb8-93e1-36b81aa9fb36)

### Steps to reproduce

1. Go to Settings
2. Click BugSnag
3. Observe theres no Blacklist field

### Craft CMS version

4.4.11

### Plugin version

4.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/bugsnag:"dev-craft-4 as 4.0.0`

**Comment by engram-design** [comment]
Fixed in [4.0.1](https://github.com/verbb/bugsnag/releases/tag/4.0.1)
