### ISSUE TITLE
yii\web\NotFoundHttpException: Template not found:

### ISSUE THREAD

**Issue by my2ter** [sjelfull/craft3-bugsnag#5]
Hi,

Would be nice to have a settings that deactivate those errors. A lot of bots will trigger that 404 error
which I think creates noise. Happy to submit a PR, but don't think I've got time to look into this right now.

Cheers

**Comment by sjelfull** [comment]
It was my intention to add filtering, but I see that it wasn't included in the current release.

Same problem here, I don't have much time at the moment. Would appreciate a PR, but I'll see if I can squeeze in some time asap for this.

**Comment by my2ter** [comment]
@sjelfull this was too painful, I create a PR for you ;) Not sure that's the what you had in mind tho

**Comment by my2ter** [comment]
@sjelfull Have you had a chance to look into it?

**Comment by sjelfull** [comment]
Yes, it mostly looks good. I just think it should be clearer what the "blacklist" consists of (classes).

Probably will rename it to `blacklistClasses`, `excludeClasses` or something similar. What do you think? 

Is there anything else we want to exclude? Exception codes? Certain user groups?

**Comment by my2ter** [comment]
Fair enough. If you start including other type of exclusions maybe the generic term "blacklist" becomes more obvious. Maybe the table should be something like:

Label -> Type -> Value

Type could be "class" / "code" / "something else" and the logic associated with it.

**Comment by nicolasbinet** [comment]
Will you publish a new release including this new settings ?

**Comment by mattcdavis1** [comment]
One issue i'm seeing here is that some exceptions may need additional logic run to see whether they should be ignored.  For example, when i use `{% exit 404 %}` in a Twig template it throws a `yii\web\HttpException`.  The problem with this is that at `yii\web\HttpException` can have any status code.  So i don't want to just ignore `yii\web\HttpException` - i only want to ignore it if it is a 404 HttpException.  I think that there needs to be a callback option for scenarios like this.

**Comment by sunscreem** [comment]
This is working for me - needed to add the blacklist via the settings though - maybe worth adding to the docs?

**Comment by sjelfull** [comment]
@mattcdavis1 Tagged 2.0.3 now, which lets you use callbacks like this to ignore specific status codes:

```php
<?php
return [
  'blacklist' => [
          [
              'label' => '404 errors etc',
              'class' => function($exception) {
                  /**
                   * @var \yii\web\NotFoundHttpException $exception
                   */
                  if ($exception instanceof \yii\web\NotFoundHttpException && $exception->statusCode === 404) {
                      return false;
                  }
  
                  return true;
              },
          ],
      ],  
];
```

**Comment by mattcdavis1** [comment]
great - thanks!
